export const TEXTS = {
  NAME: "Gurjung.Singh",
  DEV: "Front-End Developer",
  NAVBAR: {
    HOME: "home",
    SKILLS: "skills",
    PROJECTS: "projects",
    RESUME: "resume",
    CONTACT: "contact",
  },
  INTRO: {
    TITLE: "Let's build something legendary together",
    SUBTITLE: "Hi, I'm Gurjung",
    DESCRIPTION1: "A Front-End Web Developer",
    DESCRIPTION2: "Building beautiful and responsive web applications",
  },
  CONNECT: "Let's Connect",
  TECH: {
    HTML: "HTML5",
    CSS: "CSS3",
    JS: "Javascript",
    REACT: "React",
    REDUX: "Redux",
    NEXT: "NEXT JS",
    MUI: "Material UI",
    TAILWIND_CSS: "Tailwind CSS",
    CHART_JS: "Chart.js",
    FIREBASE: "Firebase",
  },
  TECHSTACK: "Tech Stack",
  CAN_DO: "What I Can Do",
  PROJECT_TITLE: "Projects",
  PROJECTS: {
    NOTES_APP: "Notes App",
    COVID_APP: "Covid19 Tracker",
    CRYPTO_APP: "Cryptocurrency Tracker",
  },
  HAVE_BUILT: "What I've Built",
  MORE_INFO: "More Info",
  CONTACT:{
    TITLE: "Contact",
    IN_TOUCH:"Get In Touch",
    AVAILABILITY: "I am available for full-time positions. Contact me and let's talk.",
    CONNECT: "Connect With Me",
    FORM:{
      NAME:"Name",
      NUMBER: "Phone Number",
      EMAIL: "Email",
      SUBJECT: "Subject",
      MESSAGE: "Message",
      SUBMIT: "Send Message",
      SUCCESS: "Email sent successfully",
      ERROR: "Email not sent",
    },
  },
  SOCIAL:{
    GITHUB:"https://github.com/gurjung",
    LINKEDIN: "https://www.linkedin.com/in/gurjung-singh-945731219",
  }
};
