export const TEXTS = {
  NAME: "Gurjung.Singh",
  NAVBAR: {
    HOME: "home",
    SKILLS: "skills",
    PROJECTS: "projects",
    RESUME: "resume",
    CONTACT: "contact",
  },
  INTRO: {
    TITLE: "Let's build something legendary together",
    SUBTITLE: "Hi, I'm Gurjung",
    DESCRIPTION1: "A Front-End Web Developer",
    DESCRIPTION2: "Building beautiful and responsive web applications",
  },
  CONNECT: "Let's Connect",
  TECH: {
    HTML: "HTML5",
    CSS: "CSS3",
    JS: "Javascript",
    REACT: "React",
    REDUX: "Redux",
    NEXT: "NEXT JS",
    MUI: "Material UI",
    TAILWIND_CSS: "Tailwind CSS",
    CHART_JS: "Chart.js",
    FIREBASE: "Firebase",
  },
  TECHSTACK: "Tech Stack",
  CAN_DO: "What I Can Do",
  PROJECT_TITLE: "Projects",
  PROJECTS: {
    NOTES_APP: "Notes App",
    COVID_APP: "Covid19 Tracker",
    CRYPTO_APP: "Cryptocurrency Tracker",
  },
  HAVE_BUILT: "What I've Built",
  MORE_INFO: "More Info",
};
