import Head from "next/head";
import { Navbar, Main, Skills, Projects, Contact } from "../components";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export default function Home() {
  return (
    <>
    <div>
      <Head>
        <title>Gurjung Singh | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Main />
      <Skills />
      <Projects />
      <Contact />
    </div>
    <ToastContainer autoClose={1000} theme="colored"/>
    </>
  );
}
