import Head from "next/head";
import { Navbar } from "../components";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Gurjung Singh | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
    </div>
  );
}
